src/Entity/UTILISATEUR.php
<?php

namespace App\Entity;

use App\Repository\UTILISATEURRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UTILISATEURRepository::class)
 */
class UTILISATEUR
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $MOT_DE_PASSE;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(?string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getMOTDEPASSE(): ?string
    {
        return $this->MOT_DE_PASSE;
    }

    public function setMOTDEPASSE(string $MOT_DE_PASSE): self
    {
        $this->MOT_DE_PASSE = $MOT_DE_PASSE;

        return $this;
    }
}

src/Controller/LoginController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class LoginController extends AbstractController
{
    /**
     * @Route("/login", name="login")
     */
    public function index(): Response
    {
        return $this->render('login/index.html.twig', [
            'controller_name' => 'LoginController',
        ]);
    }
}

templates/login/CreateLogin.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello LoginController!{% endblock %}

{% block body %}

<!DOCTYPE html>
	<html>
			<head>
				<meta charset="UTF-8" />
				
				<!-- BOOSTSTRAP CSS -->
				<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

				<!-- CODE CSS -->
				<style>
				</style>
			</head>
			
			<body>
			
				<h1>Hello</h1
			
			</body>
	</html>
{% endblock %}

templates/login/EchecAjoutUser.html.twig
{% block title %}Hello LoginController!{% endblock %}

{% block body %}

	<p> {{Infomation}}  </p>

{% endblock %}

templates/login/Erreur.html.twig
{% block title %}Hello LoginController!{% endblock %}

{% block body %}

	<p> {{erreur}}  </p>

{% endblock %}

templates/login/ListeUtilisateur.html.twig
{% block title %}Liste des Utilisateurs{% endblock %}

{% block body %}
	
	<!-- Affichage de la liste -->
	
	<table class="table table-hover">
		<thead>
			<tr>
				<th scope="col">Id</th>
				<th scope="col">Identifiant</th>
				<th scope="col">Nom</th>
				<th scope="col">Prenom</th>
			</tr>
		</thead>
		
		<tbody>
			<!-- Une boucle qui va permettre de lire toute la base de donnée -->
			
			{% for item in ListeUser %}
			<tr class=table-active">
				<td>{{ item.id}}</td>
				<td>{{ item.email}}</td>
				<td>{{ item.nom}}</td>
				<td>{{ item.prenom}}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/login/index.html.twig
{% block title %}Hello LoginController!{% endblock %}

{% block body %}

	<p> {{message}} {{nom}}<br/> {{erreur}}  </p>

{% endblock %}